language: node_js
node_js:
  - node
services:
  - neo4j
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_deploy:
  - npm run build-client
  - rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: and-the-winner-is
  api_key:
    secure: "aBF1exoalnYS+QcEgerYpoAk6Ep9M7xNxkGLiun3F6zHQu7vrBKrYVOZq75U7rBEyVMRa7swJuOvSiJhE2Ce+E5jNlLW7Gqh6t8ri8sDanlWTG5SnmxMFvzXB+zYAtZ4159T/ngg6caLdZTFAkRsEsgcWkL7SIhrKWRXT09Shjmy1lRgxd6J/RMq8FtOlCpIEbh04LZOpuDSpJ87rGaWMVqP43PQ2i0G4iAwJLLrcbwtqz7yUP3C4BIeof0xRWp7O7UjxMdYpT/aKCYHXwhmi2X+0qKCkH+ufBCNy8H3DN2rIGozD4RgvSoUnVJRSkYPCkHl5W9D3i3Y/ll+6HwvyxlBgnDQFlHmMDoslYj9L//CBfgWnA2DrWVpB2PcKXJEDKqc/pMa1ImGPzgGcJWIdbIpWBSozQshUG7i+LAJ0LGRd0wypZgbWqHHnzfkSmuWeA5MrFZM56nN61Vaap8BpgwfCiS/uvQBNFsNwg5dK20u+8KdAfVfWSlrOQ8nrauz+mosxIQfHqJ+1pvmq5g8xAZSl+EsSze5R0fnkIZhmZAJ8IE5aPdYajk6Ae+w2E4Ggnte9Ygz6wtQaXiwq3iNaL47l6nfXyvdlZEYhSQqS8Hsdo52DQgE/HsfJfouDpDyQkfYkIqiMmK82k0ve/ErQy3bQrgqXuxCoZgXrZlA6Mk="
